spring.application.name=Grocery

spring.datasource.url=jdbc:mysql://localhost:3306/grocery?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080
server.servlet.context-path=/api/v1
logging.level.org.springframework.security=DEBUG
google.client.id=108444869151-sm4m40k1mlpge5d4qchg7f5l7inp0vpd.apps.googleusercontent.com



